version: '3'

services:
  database:
    image: "mysql:latest"
    container_name: "db-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "employee"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
    networks:
      - "mynet"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy 
    networks:
      - "mynet"

networks:
  mynet:
    driver: "bridge"